<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-06-18T21:19:56 IST" name="Default suite" finished-at="2024-06-18T21:20:08 IST" duration-ms="11908">
    <groups>
    </groups>
    <test started-at="2024-06-18T21:19:56 IST" name="Default test" finished-at="2024-06-18T21:20:08 IST" duration-ms="11908">
      <class name="DataDrivenTesting.DataDrivenTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:DataDrivenTesting.DataDrivenTest@25fb8912]" started-at="2024-06-18T21:19:56 IST" name="setup" finished-at="2024-06-18T21:19:58 IST" duration-ms="2497" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:DataDrivenTesting.DataDrivenTest@25fb8912]" started-at="2024-06-18T21:20:00 IST" name="loginTest" data-provider="LoginData" finished-at="2024-06-18T21:20:03 IST" duration-ms="2478" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[9112997072']]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Choure@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Valid]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at DataDrivenTesting.DataDrivenTest.loginTest(DataDrivenTest.java:54)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="loginTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:DataDrivenTesting.DataDrivenTest@25fb8912]" started-at="2024-06-18T21:20:03 IST" name="loginTest" data-provider="LoginData" finished-at="2024-06-18T21:20:05 IST" duration-ms="2393" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[9112997073']]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Choure@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Invalid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="loginTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:DataDrivenTesting.DataDrivenTest@25fb8912]" started-at="2024-06-18T21:20:05 IST" name="loginTest" data-provider="LoginData" finished-at="2024-06-18T21:20:06 IST" duration-ms="1156" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[9637515958']]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Choure@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[valid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method signature="loginTest(java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:DataDrivenTesting.DataDrivenTest@25fb8912]" started-at="2024-06-18T21:20:06 IST" name="loginTest" data-provider="LoginData" finished-at="2024-06-18T21:20:07 IST" duration-ms="1252" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[9850080854']]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA["Choure@123"]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Invalid]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:DataDrivenTesting.DataDrivenTest@25fb8912]" started-at="2024-06-18T21:20:08 IST" name="tearDown" finished-at="2024-06-18T21:20:08 IST" duration-ms="165" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- DataDrivenTesting.DataDrivenTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
